#!/usr/bin/env python

import sys
import re
import os
from os import path

arg_dict = {
    'to': '',
    'hastext': '',
    'fdirs': 'files'
}

if '-h' in sys.argv or '--help' in sys.argv:
    print('''example of usage:''')
    print('''    renamer path=/path/to/dir/ hastext='some text' from='replacing' to='replacement' fdirs=[files|dirs|both]''')
    print('''defaults:''')
    for i in arg_dict:
        print(f'    {i}={arg_dict[i]}')
    sys.exit(0)

for i in sys.argv[1:]:
    k, v = i.split('=')
    arg_dict[k] = v

if 'path' in arg_dict:
    try:
        os.chdir(arg_dict['path'])
    except FileNotFoundError:
        print('''Can't find directory''')
        os.exit(0)
    except PermissionError:
        print('''Don't have read permission''')
        os.exit(0)
    else:
        print('Switching directory to {}'.format(os.getcwd()))

fdirs = os.listdir()
if arg_dict['fdirs'] == 'files':
    fdirs = filter(path.isfile, fdirs)
elif arg_dict['fdirs'] == 'dirs':
    fdirs = filter(path.isdir, fdirs)

for name in sorted(fdirs):
    if arg_dict['hastext'] in name:
        new_name = re.sub(r''.join(arg_dict['from']), arg_dict['to'], name)
        try:
            os.rename(name, new_name)
        except PermissionError:
            print('''Don't have write permission''')
        else:
            print(f'''{name} -> {new_name}''')
